name: CI
on: [push, pull_request]

jobs:
  Windows-unittest:
    name: Windows unittest - ${{ matrix.PYTHON_VERSION }}
    runs-on: windows-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.6']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: lleaves
          environment-file: environment.yml
          use-only-tar-bz2: true
          use-mamba: true
      - name: Run the unittests
        shell: bash -x -l {0}
        run: |
          pip install --no-use-pep517 --no-deps --no-build-isolation --disable-pip-version-check -e .
          pytest -v tests

  pre-commit-checks:
    name: "Pre-commit checks - Python 3.9"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0